import argparse
import pandas as pd
import h5py
import numpy as np

def process_tis(csv_path, input_h5_path, output_h5_path):
    # Load CSV looks for 'transcript_id' and 'TIS_pos' columns
    new_tis_df = pd.read_csv(csv_path)
    new_tis_df = new_tis_df[['transcript_id', 'TIS_pos']]
    result = new_tis_df.groupby('transcript_id')['TIS_pos'].apply(set).to_dict()

    # Open HDF5 files
    with h5py.File(input_h5_path, 'r') as file, h5py.File(output_h5_path, 'a') as new_file:
        if 'transcript' not in new_file:
            new_file.create_group('transcript')

        # Copy the Original data except for the 'tis'
        for name in file['transcript']:
            if name != 'tis':
                new_file['transcript'].create_dataset(name=name, data=file['transcript'][name][()])

        #creates a list of arrays of the same size as the number of transcripts in the h5 file, 
        # each array is copied from the original h5 

        tis_list = []
        transcript_ids = new_file['transcript']['transcript_id']
        for j, id_bytes in enumerate(transcript_ids):
            arr = file['transcript']['tis'][j][()]
            transcript_id = id_bytes.decode('utf-8')
            #adds the new TIS to the array if the transcript_id is in the csv file
            if transcript_id in result:
                for tis in result[transcript_id]:
                    if tis > 20: # Assumes the transcripts UTRs are complete, a ribosome can not start translation before the 20th nucleotide of an mRNA
                                # Doesnt affect Orginal TIS annotated by TIS_transformer even if they dont respect this above
                        arr[tis - 1] = 1
            tis_list.append(arr)

        # h5 formatting for variable length arrays of int8
        tis_list_array = np.array(tis_list, dtype=object)
        vlen_dtype = h5py.special_dtype(vlen=np.dtype('int8'))
        new_file['transcript'].create_dataset(name='tis', data=tis_list_array, dtype=vlen_dtype)

def main():
    parser = argparse.ArgumentParser(description="Process TIS data and update HDF5 files.")
    parser.add_argument('--csv', required=True, help='Path to csv containing col transcript_id and TIS_pos of the new TIS to add, \n TIS pos should be 1-based position of the TIS on the transcript')
    parser.add_argument('--input_h5', required=True, help='Path to input h5 parsed ensembl transcriptome generated by the first step of TIS_transformer package')
    parser.add_argument('--output_h5', required=True, help='Path to the new h5 file to create with the new TIS added')
    args = parser.parse_args()

    process_tis(args.csv, args.input_h5, args.output_h5)

if __name__ == "__main__":
    main()